apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: spring-sensors-rabbit
  annotations:
    'backstage.io/techdocs-ref': dir:.
    'backstage.io/kubernetes-label-selector': 'carto.run/workload-name=spring-sensors-consumer-web'
  tags:
    - app-accelerator
    - java
    - spring
    - web
    - tanzu
spec:
  type: service
  lifecycle: production
  owner: default-team
  system: backstage
