apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: tap-gui-catalog-info
  description: A sample catalog for Backstage
  annotations:
    'backstage.io/techdocs-ref': dir:.
        'backstage.io/kubernetes-label-selector': 'app=backstage'
spec:
  type: service
  lifecycle: experimental
  owner: defaul-team
  system: backstage
  dependsOn: [Component:backstage]
  targets:
    - ./components/tap-gui.yaml
    - ./groups/default-org.yaml
    - ./systems/tap-gui-system.yaml
    - ./domains/tap-gui-domain.yaml
    - ./components/java-web-app.yaml
    - ./components/spring-petcilinc.yaml
    - ./components/spring-sensor-producer.yaml
    - ./components/spring-sensor-consumer.yaml
